### ISSUE TITLE
No Audio Packets. Only Heartbeat

### ISSUE THREAD

**Issue by promikey** [amigniter/mod_audio_stream#14] opened 2023-11-12 06:55 UTC
On FreeSWITCH Version 1.10.10-release-24-4cb05e7f4a~64bit (-release-24-4cb05e7f4a 64bit)

I'm getting the heartbeat from mod_audio_stream but no audio packets on the receiving websocket app. Doesnt appear to be working with 1.10.10-release-24. I've tried changing all the settings (mono/stereo, 8k/16k) but no luck. Any ideas?

sudo tcpdump -i any -nn port 7771
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
06:46:29.890446 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [S], seq 1960437859, win 43690, options [mss 65495,nop,nop,sackOK,nop,wscale 10], length 0
06:46:29.890461 IP 127.0.0.1.7771 > 127.0.0.1.31478: Flags [S.], seq 2823104063, ack 1960437860, win 43690, options [mss 65495,nop,nop,sackOK,nop,wscale 10], length 0
06:46:29.890474 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [.], ack 1, win 43, length 0
06:46:29.890531 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [P.], seq 1:323, ack 1, win 43, length 322
06:46:29.893616 IP 127.0.0.1.7771 > 127.0.0.1.31478: Flags [P.], seq 1:204, ack 323, win 43, length 203
06:46:29.893629 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [.], ack 204, win 43, length 0
06:46:29.894008 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [P.], seq 323:338, ack 204, win 43, length 15
06:46:29.894182 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [P.], seq 338:373, ack 204, win 43, length 35
06:46:29.894826 IP 127.0.0.1.7771 > 127.0.0.1.31478: Flags [.], ack 373, win 43, length 0
06:46:29.895811 IP 127.0.0.1.7771 > 127.0.0.1.31478: Flags [P.], seq 204:235, ack 373, win 43, length 31
06:46:29.937700 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [.], ack 235, win 43, length 0
06:46:30.895021 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [P.], seq 373:408, ack 235, win 43, length 35
06:46:30.896297 IP 127.0.0.1.7771 > 127.0.0.1.31478: Flags [P.], seq 235:266, ack 408, win 43, length 31
06:46:30.896318 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [.], ack 266, win 43, length 0
06:46:31.895423 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [P.], seq 408:443, ack 266, win 43, length 35
06:46:31.895903 IP 127.0.0.1.7771 > 127.0.0.1.31478: Flags [P.], seq 266:297, ack 443, win 43, length 31
06:46:31.895922 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [.], ack 297, win 43, length 0
06:46:32.896035 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [P.], seq 443:478, ack 297, win 43, length 35
06:46:32.896517 IP 127.0.0.1.7771 > 127.0.0.1.31478: Flags [P.], seq 297:328, ack 478, win 43, length 31
06:46:32.896537 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [.], ack 328, win 43, length 0
06:46:33.896645 IP 127.0.0.1.31478 > 127.0.0.1.7771: Flags [P.], seq 478:513, ack 328, win 43, length 3

Receiving APP
2023-11-12 06:46:29.894 - DEBUG - [MainThread] read_frame() - < TEXT 'testing11111' [9 bytes]
2023-11-12 06:46:29.895 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::0' [text, 29 bytes]
2023-11-12 06:46:29.895 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::0' [text, 29 bytes]
2023-11-12 06:46:29.896 - INFO - [MainThread] websocket_server() - Received packet: 9 bytes.
2023-11-12 06:46:30.895 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::1' [text, 29 bytes]
2023-11-12 06:46:30.895 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::1' [text, 29 bytes]
2023-11-12 06:46:31.895 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::2' [text, 29 bytes]
2023-11-12 06:46:31.895 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::2' [text, 29 bytes]
2023-11-12 06:46:32.896 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::3' [text, 29 bytes]
2023-11-12 06:46:32.896 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::3' [text, 29 bytes]
2023-11-12 06:46:33.896 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::4' [text, 29 bytes]
2023-11-12 06:46:33.897 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::4' [text, 29 bytes]
2023-11-12 06:46:34.897 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::5' [text, 29 bytes]
2023-11-12 06:46:34.897 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::5' [text, 29 bytes]
2023-11-12 06:46:35.898 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::6' [text, 29 bytes]
2023-11-12 06:46:35.898 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::6' [text, 29 bytes]
2023-11-12 06:46:36.248 - INFO - [MonitoringThread] _monitor_and_restart_process() - Event processor process is alive...
2023-11-12 06:46:36.898 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::7' [text, 29 bytes]
2023-11-12 06:46:36.898 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::7' [text, 29 bytes]
2023-11-12 06:46:37.899 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::8' [text, 29 bytes]
2023-11-12 06:46:37.899 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::8' [text, 29 bytes]
2023-11-12 06:46:38.899 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::9' [text, 29 bytes]
2023-11-12 06:46:38.899 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::9' [text, 29 bytes]
2023-11-12 06:46:39.900 - DEBUG - [MainThread] read_frame() - < PING 'ixwebsocket::heartbeat::1s::10' [text, 30 bytes]
2023-11-12 06:46:39.900 - DEBUG - [MainThread] write_frame_sync() - > PONG 'ixwebsocket::heartbeat::1s::10' [text, 30 bytes]
2023-11-12 06:46:39.972 - DEBUG - [MainThread] read_frame() - < CLOSE 1000 (OK) Normal closure [16 bytes]

2023-11-12 06:46:29.885577 98.37% [DEBUG] mod_audio_stream.c:144 mod_audio_stream cmd: 5f2c514d-7cfb-4017-ae7c-616003327cd6 start ws://127.0.0.1:7771/?channel_uuid=5f2c514d-7cfb-4017-ae7c-616003327cd6 stereo 16k testing11111
2023-11-12 06:46:29.885577 98.37% [DEBUG] mod_audio_stream.c:75 calling stream_session_init.
2023-11-12 06:46:29.885577 98.37% [DEBUG] audio_streamer_glue.cpp:252 (5f2c514d-7cfb-4017-ae7c-616003327cd6) resampling from 8000 to 16000
2023-11-12 06:46:29.885577 98.37% [DEBUG] audio_streamer_glue.cpp:263 (5f2c514d-7cfb-4017-ae7c-616003327cd6) stream_data_init
2023-11-12 06:46:29.885577 98.37% [DEBUG] mod_audio_stream.c:81 adding bug.
2023-11-12 06:46:29.885577 98.37% [DEBUG] switch_core_media_bug.c:976 Attaching BUG to sofia/external/5555555555@mydomain.com
2023-11-12 06:46:29.885577 98.37% [DEBUG] mod_audio_stream.c:85 setting bug private data.
2023-11-12 06:46:29.885577 98.37% [DEBUG] mod_audio_stream.c:88 exiting start_capture.
2023-11-12 06:46:29.885577 98.37% [DEBUG] switch_cpp.cpp:1465 uuid_audio_stream Response: +OK Success
2023-11-12 06:46:29.885577 98.37% [DEBUG] switch_cpp.cpp:1465 uuid_audio_stream Response: +OK Success
2023-11-12 06:46:29.885577 98.37% [DEBUG] audio_streamer_glue.cpp:110 sending initial metadata mike11111
2023-11-12 06:46:29.925582 98.37% [DEBUG] switch_core_io.c:448 Setting BUG Codec PCMU:0

**Comment by amigniter** [comment] 2023-11-12 10:21
Is there any audio on the channel? Media bug will be triggered when there is a media on the channel, and looks to me there is actually no audio on the channel to be streamed.
Since default call is in mono 8k, in this case you're resampling it to stereo 16k. That's perfectly fine if that's what you need, but I'd expect speex resampler to be activated and I don't see it working among the debug lines. Definitely there is no audio and that's why there are no audio packets at the endpoint.

**Comment by promikey** [comment] 2023-11-12 21:40
@amigniter yes there is audio on the channel. I can hear audio on both legs of the call.

**Comment by alex-at-voxsmart** [comment] 2023-11-15 10:00
Have the same issue. Happens when sip client send re-invite after initial invite is accepted. not much is updated in the second invite:
- SDP/owner/session_version
- SDP/media_attr: sendrecv ->sendonly
- SDP/media_description: added media_format ITU-T G.722

When there is no re-invite, everything works fine.

**Comment by amigniter** [comment] 2023-11-15 17:41
We are working on it, trying to find out why there are no packets sent (want to fully reproduce it). If there is a bug it will be solved definitely.

**Comment by alex-at-voxsmart** [comment] 2023-11-16 20:15
I have resolved by issue by changing a configuration of free switch:
 
sendolny from the client side sets call to onhold on FS side (very useful post https://nickvsnetworking.com/sip-hold-with-rfc6337/). When a call it in HELD state, nothing is forwarded to the WebSocket channel - I see lots of RTP arriving, but on WebSocket side are only some keepalives. When a call is in ACTIVE state everything works fine.

Was able to overcome this by setting rtp_disable_hold=true variable. after this variable is set, a call is never moved to a HELD state and stays in ACTIVE state regardless of media_attribute value received. Simply added `<action application="set" data="rtp_disable_hold=true" />` in a dialplan. not sure this is a best approach, but it works for me.

**Comment by promikey** [comment] 2023-11-16 21:48
@alex-at-voxsmart I wish that worked for me too. In my case the call is not held as I see the media attribute "a=sendrecv"

**Closed** 2023-12-01 11:37 UTC
