### ISSUE TITLE
[bug] Crashing FreeSWTICH after the "calling stream_session_init" (occurs occasionally)

### ISSUE THREAD

**Issue by hizbi-github** [amigniter/mod_audio_stream#39] opened 2024-07-09 18:43 UTC
Hi @amigniter, thanks for the great tool. It's really straight forward and works great.

I just noticed an issue recently. The module seems to crash FS. The latest most crash seemed to have happened after this log:
`2087f28c-ebb1-435f-b1c7-3020c413bacf 2024-07-09 11:25:24.656077 40.93% [DEBUG] mod_audio_stream.c:75 calling stream_session_init.`

I can also see this in my syslog:
`Jul  9 11:25:24 freeswitch-staging kernel: [29704443.783812] freeswitch[419400]: segfault at 8 ip 00007fd3ca9ddd59 sp 00007fd4096b72c0 error 4 in mod_audio_stream.so[7fd3ca9d7000+3a000]
Jul  9 11:25:24 freeswitch-staging kernel: [29704443.796208] Code: 8d 15 d3 38 03 00 50 48 8d 35 c3 32 03 00 31 c0 e8 0c a3 ff ff 48 8b 44 24 28 45 89 f9 4c 89 f1 48 8d 35 8a f6 ff ff 4c 89 ef <48> 8b 40 08 8b 50 1c 48 8d 44 24 38 50 ff 74 24 20 44 8b 44 24 34`

FreeSWITCH version (build from GitHub source):
`FreeSWITCH Version 1.10.10-release+git~20230813T165739Z~4cb05e7f4a~64bit (git 4cb05e7 2023-08-13 16:57:39Z 64bit)`

OS:
`Debian 11 Bullseye`

I know you are probably occupied yourself, please have a look when are comfortable.
Let me know if you need any other information from logs.

Thanks!

**Comment by amigniter** [comment] 2024-07-09 19:27
> Hi @amigniter, thanks for the great tool. It's really straight forward and works great.

You're welcome, and thank you for kind words.

> Let me know if you need any other information from logs.

Yes, please give me all the info you have. We really don't have any issues at all (though using 1.10.11) but there shouldn't be any issues with older versions either. Can you tell me how are you calling the API, and how to reproduce the issue? I am pretty much sure it's not because of this module, but we'll see.

**Comment by amigniter** [comment] 2024-07-10 11:22
@hizbi-github 

Tested with 1.10.10 built from source as well, and there were no issues at all.
Our version was built using release tar 1.10.10 from [freeswitch files](https://files.freeswitch.org/releases/freeswitch/) and it should be the same version.

If you can reproduce the bug you faced please let me know.

**Comment by amigniter** [comment] 2024-07-11 20:38
>Do you want me to provide the WebSockets endpoint so you can test the connection yourself?

Just the endpoint won't help in this case. We need to reproduce entire call flow to see what is happening and why.

Unfortunately from this console log I can't see what is exactly happening and why there is a crash. A real core|crash dump will be extremely useful here (which I could later load into gdb). If you know how to create one it would be extremely helpful.

This module reached a pretty solid state, but of course, anything can happen. Also, improper use of a channel can lead to a FS crash (not using this module, generally speaking). Make sure the call reached the answered state. Something weird is happening, like something is executing prematurely. Can you test with something else on the channel (instead of mod_audio_stream), start recording or anything else to see what happens in the same scenario. There is a check before stream_init to make sure it passed pre_answer state, but it is all telling me that something is wrong with the channel. The channel exists but looks like it is not ready yet (besides passing the mentioned check). When we identify what is happening I will definitely introduce an additional check. At this point I am sure the channel is not ready yet and the streamer can't be used at the current state of the channel (so in such a situation it should just cleanly exit).

**Comment by hizbi-github** [comment] 2024-07-12 12:02
@amigniter Thanks for replying.

I have now enabled coredump, so as soon as I detect the crash, I will share the dump here.

And regarding the channel state, I am sure the mod_audio_stream is initiated after the channel is answered, as I can see the CHANNEL_ANSWER event coming in before the CHANNEL_PARK event where I start audio streaming.

Here's the call flow:
1. bgapi originates a call to leg_a (will be connected to leg_b_dialplan)
2. leg_a answers
3. leg_b_dialplan executes the "park" application
4. on CHANNEL_PARK event, a Lua script runs the uuid_audio_stream
5. streaming starts

Does the callflow makes sense?

**Comment by hizbi-github** [comment] 2024-07-19 10:26
Hi @amigniter, just an update.

I had enabled the core dump, but ironically it has not crashed since then even once.
I will share the dump as soon as I detect the crash.

Thanks!

**Comment by amigniter** [comment] 2024-07-20 10:28
@hizbi-github Thanks for the update.

Regarding the module, it is fine. What could possibly happen is maybe a race condition (events, bgapi, etc). So what you could do is improve your lua scripts a bit, add checks whether a channel is ready (channel state checks) and so on. This way you are absolutely sure you are not calling API on a channel that's not ready yet.
I am closing the issue now. If you face the same issue again please re-open it and we'll deal with it.
BR

**Closed by amigniter** 2024-07-20 10:28 UTC
